_wandb:
    value:
        cli_version: 0.21.0
        e:
            4t6u8g2b5uaun1xincryc90kfbommcaa:
                codePath: scripts/train_with_uncertainty_full.py
                codePathLocal: scripts/train_with_uncertainty_full.py
                email: arvindster@gmail.com
                executable: /Users/ramanathana/miniconda3/bin/python
                host: Arvinds-MacBook-Pro.local
                os: macOS-26.0-arm64-arm-64bit
                program: /Users/ramanathana/Documents/augment-projects/APAS-SB/scripts/train_with_uncertainty_full.py
                python: CPython 3.12.11
                root: /Users/ramanathana/Documents/augment-projects/APAS-SB
                startedAt: "2025-11-01T02:58:28.837738Z"
                writerId: 4t6u8g2b5uaun1xincryc90kfbommcaa
        m: []
        python_version: 3.12.11
        t:
            "1":
                - 1
                - 105
            "2":
                - 1
                - 105
            "3":
                - 13
                - 16
            "4": 3.12.11
            "5": 0.21.0
            "12": 0.21.0
            "13": darwin-arm64
min_weight:
    value: 0.1
n_epochs:
    value: 10
resolution_stratify:
    value: true
weighting_scheme:
    value: inverse_variance
